#!/bin/sh

#==============#
# X11
#==============#
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources # Merge Xresources
xset b off # Disables bell
xset -dpms # Disables Energy Star features
xset s off # Disables screen saver
setxkbmap -option caps:escape # Make Caps an additional Escape

#==============#
# Session
#==============#
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets)
export SSH_AUTH_SOCK

#==============#
# Display
#==============#
xrandr --output eDP-1 --set "scaling mode" "Full"
xinput | grep 'ELAN224A' | grep 'pointer' | grep -Po 'id=\d+' | cut -d= -f2 | xargs xinput disable

#==============#
# Compositor
#==============#
[ -x ~/.icewm/restart ] && source ~/.icewm/restart

#==============#
# Wallpaper
#==============#
#feh --bg-tile ~/Pictures/Wallpapers/bitmaps/408.png &
feh --bg-tile ~/.icewm/bg.png &
#hsetroot -solid "#898989"

#==============#
# Notifications
#==============#
dunst &

#==============#
# Tray Icons
#==============#
# start network manager
sleep 1 && nm-applet &

# start power manager
#sleep 1 && xfce4-power-manager &

# start bluetooth manager
sleep 1 && blueman-applet &

# start matebook applet
#sleep 1 && ~/git/matebook-applet/matebook-applet &

# start dropbox
sleep 1 && dropbox start -i &

#==============#
# Daemons
#==============#
# start gestures service
libinput-gestures &

# start Emacs
if pgrep -x "emacs" > /dev/null
then
    echo "emacs is already running" > /dev/null
else
    emacs --daemon &
fi

#==============#
# Oneshot
#==============#
# ROG KERIS
if xinput list | grep "ROG KERIS  " > /dev/null
then
    sleep 1 && ~/bin/kmaccel
else
    echo "ROG KERIS not plugged in" > /dev/null
fi

# Viper Mini
if xinput list | grep "Viper Mini  " > /dev/null
then
    sleep 1 && ~/bin/kmviperaccel
else
    echo "Viper Mini not plugged in" > /dev/null
fi
