alias cls='clear'
alias whereami='echo $PWD'
alias whatami='cat /etc/hostname'
alias naptime='sudo systemctl suspend'
alias temps='watch -n .1 sensors'
alias getip="curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'"
alias rip='grep --color=auto'
alias e='$EDITOR '
alias m='mousepad '
alias c='cat '
alias gstat='git status'
alias gpull='git pull'
alias gpush='git push origin master'
alias gb='git branch'
alias gadd='git add -A'
alias gcom='git commit'
alias pkgcount='dpkg -l | grep -c ^i'
alias silence_of_the_fans='sudo powertop --auto-tune'
alias ytmp3='youtube-dl --extract-audio --audio-format mp3 '
alias tl='tmux list-session'
alias tk='tmux kill-session'
alias tn='tmux new'
alias ta='tmux attach'
alias weather='curl wttr.in/cmb?0'
alias weatherfull='curl wttr.in/cmb'
alias f='fzf'
alias redditfetch='neofetch'
alias randvid='mpv --shuffle ~/Videos/'
alias up='uptime -p'
alias soff='mpc single off'
alias doas="sudo"
alias pkg="pacman"
alias music="ncmpcpp"
alias scrotum="scrot -d 1"
alias sxiv='sxiv -b'
alias py='python3'
alias ff='firefox'
alias enlarge_tmp='sudo mount -o remount,size=16G /tmp/'

#games
alias mc='java -jar ~/games/mc.jar'
alias doom='gzdoom /home/diamond/.config/gzdoom/brutalv21.pk3'
alias nfsmw='cd ~/games/nfsmw; wine nfsmwres.exe'
alias gtavc='cd ~/games/gtavc; wine gta-vc.exe'
