#!/bin/bash

# X11
xrdb "/home/diamond/.Xresources"
#xset -b
xset b off &
ulimit -c unlimited

#xbindkeys &
#dunst &
#lxpolkit &
#nm-applet &
#mate-volume-control-applet &
#xfce4-power-manager &
#thunar --daemon &
#light-locker &
#compton --vsync opengl -CGb &

#while true; do
#    xsetroot -name "$(/home/diamond/bin/days) | $(/home/diamond/bin/cputemp) | $(/home/diamond/bin/battery) | $(date +%F) $(date +%I:%M)"
#    sleep 10
#done &

#hsetroot -solid "#aaaaaa"
#xrdb ~/.Xresources

#while true; do
#    /usr/local/bin/dwm 2> /dev/null
#done

#exec vtwm
#exec dbus-launch dwm
exec dbus-launch openbox-session
#exec dbus-launch wmx
